### PR TITLE
Use login_as() helper to speed up rspec run.

### PR DESCRIPTION
**Pull request by robmckinnon**
* Instead of signing in via login page for each rspec feature, use login_as() helper.
* My local test run time went from 20s down to 12s after this change.

### CODE REVIEW

**Comment by pedrosmmoreira** [comment]
While that is a considerable performance boost, I'd be reluctant to use it across all integration tests.

This is equivalent of saying "Test mode, I want to exempt you from the auth mechanism in place", which is fine: in many places, we don't actually care about the auth - just that it is in the state required. However, I would leave a scenario walking through those steps and guarding agains regression. 

Much as speed is great, it is not the only factor at play.

**Comment by pedrosmmoreira** [comment]
While that is a considerable performance boost, I'd be reluctant to use it across all integration tests.

This is equivalent of saying "Test mode, I want to exempt you from the auth mechanism in place", which is fine: in many places, we don't actually care about the auth - just that it is in the state required. However, I would leave a scenario walking through those steps and guarding against regression. 

Much as speed is great, it is not the only factor at play.

**Comment by robmckinnon** [comment]
Ok. If we add a new login feature we can explicitly test those login page steps. For the other features we just need a particular type of user to be logged in, no need to repeat the login page steps each time.

**Comment by pixeltrix** [comment]
Firstly, this has extraneous changes regarding adding rb-fsevent and removing terminal-notifier-guard - these seem orthogonal to using warder test helpers so please keep PRs atomic.

On the main changes this isn't a good idea because testing the login steps alone really amounts to replicating Devise's tests and removing them from the features runs the risks of bugs slipping through. I can think of plenty of situations where changes in an individual controller ends up with authentication bypassed and removing the login steps may prevent the detection of the problems.

The fact that features take 20s instead of 12s is pretty much irrelevant as you won't be running the full suite that often - that's the CI's job.

**Comment by ansonK** [comment]
Agree with the above. A small speed increase is not worth the risks it opens up

**Pull request closed without merging**
