### PR TITLE
Fix tabs to float correctly in low IEs

### PR DESCRIPTION
**Pull request by axemonkey**
Tested and now floating correctly in IE6-10, and still working fine in Chrome and Firefox

### CODE REVIEW

**Comment by axemonkey** [comment]
Hold it - just realised there are tabs on more than one page, and they don't work correctly on the others for some reason. Don't merge yet.

**Comment by novotnyjakub** [comment]
The tabs seem to behave differently on the defence request detail page and the dashboard. On the detail page, the tab link stays outlined after clicking on it.

**Comment by novotnyjakub** [comment]
Also I just noticed that the side bar is not there, so maybe you should rebase on master, to make sure nothing gets lost?

**Comment by axemonkey** [comment]
Ah yes. One is JS-powered and one is a full page refresh

**Comment by novotnyjakub** [comment]
I understand that, but it has an orange border when selected. I guess it's the :active state, but it looks weird. If you think it's fine, I won't block it :)

**Pull request merged**
